Get releases from github.com/accetto/tigervnc rather than BinTray

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -7,18 +7,13 @@ set -euo pipefail
 exec > >(log_stream) 2> >(error_stream)
 
 target="$ASDF_DOWNLOAD_PATH/$jar_file"
-
-# Workaround for some jar names not following the same pattern 
-case "$ASDF_INSTALL_VERSION" in
-1.3.1)
-    source='https://dl.bintray.com/tigervnc/stable/VncViewer.jar'
-    ;;
-*)
-    source="https://dl.bintray.com/tigervnc/stable/VncViewer-$ASDF_INSTALL_VERSION.jar"
-    ;;
-esac
+source="https://github.com/accetto/tigervnc/releases/download/v$ASDF_INSTALL_VERSION-mirror/VncViewer-$ASDF_INSTALL_VERSION.jar"
+curl_opts=(-L --no-progress-meter)
+if [ -n "${GITHUB_API_TOKEN:-}" ]; then
+  curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
+fi
 
 [ "$ASDF_INSTALL_TYPE" = "version" ] || { error "can only handle version installations"; exit 1; }
 
 log "downloading version $ASDF_INSTALL_VERSION"
-curl --no-progress-meter -L "$source" > "$target" || { rm -f "$target"; error "download failed"; exit 1; }
+curl "${curl_opts[@]}" "$source" > "$target" || { rm -f "$target"; error "download failed"; exit 1; }
